<?php

declare(strict_types=1);

/*
 * VerizonThingSpaceQualityOfServiceAPIEndpointsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonThingSpaceQualityOfServiceAPIEndpointsLib\Tests\Controllers;

use VerizonThingSpaceQualityOfServiceAPIEndpointsLib\Controllers\ExclusionsController;
use VerizonThingSpaceQualityOfServiceAPIEndpointsLib\Exceptions;

class ExclusionsControllerTest extends BaseTestController
{
    /**
     * @var ExclusionsController ExclusionsController instance
     */
    protected static $controller;

    /**
     * Setup test class
     */
    public static function setUpBeforeClass(): void
    {
        self::$controller = parent::getClient()->getExclusionsController();
    }

    public function testDevicesLocationGiveConsentAsync()
    {
        // Parameters for the API call
        $body = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->devicesLocationGiveConsentAsync($body);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)->expectStatus(200)->allowExtraHeaders()->expectHeaders($headers)->assert();
    }
}
