<?php

declare(strict_types=1);

/*
 * VerizonThingSpaceQualityOfServiceAPIEndpointsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonThingSpaceQualityOfServiceAPIEndpointsLib\Tests\Controllers;

use VerizonThingSpaceQualityOfServiceAPIEndpointsLib\Controllers\ThingSpaceQualityOfServiceAPIActionsController;
use VerizonThingSpaceQualityOfServiceAPIEndpointsLib\Exceptions;

class ThingSpaceQualityOfServiceAPIActionsControllerTest extends BaseTestController
{
    /**
     * @var ThingSpaceQualityOfServiceAPIActionsController ThingSpaceQualityOfServiceAPIActionsController instance
     */
    protected static $controller;

    /**
     * Setup test class
     */
    public static function setUpBeforeClass(): void
    {
        self::$controller = parent::getClient()->getThingSpaceQualityOfServiceAPIActionsController();
    }

    public function testStopAThingSpaceQualityOfServiceAPISubscription()
    {
        // Parameters for the API call
        $accountName = '0000123456-00001';
        $qosSubscriptionId =
            'QoS subscription ID';

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->stopAThingSpaceQualityOfServiceAPISubscription(
                $accountName,
                $qosSubscriptionId
            );
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)->expectStatus(201)->allowExtraHeaders()->expectHeaders($headers)->assert();
    }
}
