<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Authentication;

use Core\Utils\CoreHelper;

/**
 * Utility class for initializing VZM2MToken security credentials.
 */
class VZM2MTokenCredentialsBuilder
{
    /**
     * @var array
     */
    private $config;

    private function __construct(array $config)
    {
        $this->config = $config;
    }

    /**
     * Initializer for VZM2MTokenCredentialsBuilder
     *
     * @param string $vZM2mToken
     */
    public static function init(string $vZM2mToken): self
    {
        return new self(['vZM2mToken' => $vZM2mToken]);
    }

    /**
     * Setter for VZM2mToken.
     *
     * @param string $vZM2mToken
     *
     * @return $this
     */
    public function vZM2mToken(string $vZM2mToken): self
    {
        $this->config['vZM2mToken'] = $vZM2mToken;
        return $this;
    }

    public function getConfiguration(): array
    {
        return CoreHelper::clone($this->config);
    }
}
