<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Authentication;

use Core\Authentication\CoreAuth;
use Core\Request\Parameters\HeaderParam;

/**
 * Utility class for authorization and token management.
 */
class VZM2MTokenManager extends CoreAuth implements VZM2MTokenCredentials
{
    private $vZM2mToken;

    /**
     * Returns an instance of this class.
     *
     * @param string $vZM2mToken M2M Session Token ([How to generate an M2M session
     *        token?]($e/Session%20Management/StartConnectivityManagementSession))
     */
    public function __construct(string $vZM2mToken)
    {
        parent::__construct(HeaderParam::init('VZ-M2M-Token', $vZM2mToken)->requiredNonEmpty());
        $this->vZM2mToken = $vZM2mToken;
    }

    /**
     * String value for vZM2mToken.
     */
    public function getVZM2mToken(): string
    {
        return $this->vZM2mToken;
    }

    /**
     * Checks if provided credentials match with existing ones.
     *
     * @param string $vZM2mToken M2M Session Token ([How to generate an M2M session
     *        token?]($e/Session%20Management/StartConnectivityManagementSession))
     */
    public function equals(string $vZM2mToken): bool
    {
        return $vZM2mToken == $this->vZM2mToken;
    }
}
