<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\AccountService;

/**
 * Builder for model AccountService
 *
 * @see AccountService
 */
class AccountServiceBuilder
{
    /**
     * @var AccountService
     */
    private $instance;

    private function __construct(AccountService $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new account service Builder object.
     */
    public static function init(): self
    {
        return new self(new AccountService());
    }

    /**
     * Sets name field.
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets description field.
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Sets states field.
     */
    public function states(?array $value): self
    {
        $this->instance->setStates($value);
        return $this;
    }

    /**
     * Initializes a new account service object.
     */
    public function build(): AccountService
    {
        return CoreHelper::clone($this->instance);
    }
}
