<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\AccountConsentCreate;

/**
 * Builder for model AccountConsentCreate
 *
 * @see AccountConsentCreate
 */
class AccountConsentCreateBuilder
{
    /**
     * @var AccountConsentCreate
     */
    private $instance;

    private function __construct(AccountConsentCreate $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new account consent create Builder object.
     */
    public static function init(): self
    {
        return new self(new AccountConsentCreate());
    }

    /**
     * Sets device list field.
     */
    public function deviceList(?array $value): self
    {
        $this->instance->setDeviceList($value);
        return $this;
    }

    /**
     * Sets account name field.
     */
    public function accountName(?string $value): self
    {
        $this->instance->setAccountName($value);
        return $this;
    }

    /**
     * Initializes a new account consent create object.
     */
    public function build(): AccountConsentCreate
    {
        return CoreHelper::clone($this->instance);
    }
}
