<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\ActiveAnomalyIndicator;

/**
 * Builder for model ActiveAnomalyIndicator
 *
 * @see ActiveAnomalyIndicator
 */
class ActiveAnomalyIndicatorBuilder
{
    /**
     * @var ActiveAnomalyIndicator
     */
    private $instance;

    private function __construct(ActiveAnomalyIndicator $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new active anomaly indicator Builder object.
     */
    public static function init(): self
    {
        return new self(new ActiveAnomalyIndicator());
    }

    /**
     * Sets active field.
     */
    public function active(?bool $value): self
    {
        $this->instance->setActive($value);
        return $this;
    }

    /**
     * Initializes a new active anomaly indicator object.
     */
    public function build(): ActiveAnomalyIndicator
    {
        return CoreHelper::clone($this->instance);
    }
}
