<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\AggregateSessionReportRequest;

/**
 * Builder for model AggregateSessionReportRequest
 *
 * @see AggregateSessionReportRequest
 */
class AggregateSessionReportRequestBuilder
{
    /**
     * @var AggregateSessionReportRequest
     */
    private $instance;

    private function __construct(AggregateSessionReportRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new aggregate session report request Builder object.
     */
    public static function init(string $accountNumber, array $imei): self
    {
        return new self(new AggregateSessionReportRequest($accountNumber, $imei));
    }

    /**
     * Sets start date field.
     */
    public function startDate(?string $value): self
    {
        $this->instance->setStartDate($value);
        return $this;
    }

    /**
     * Sets end date field.
     */
    public function endDate(?string $value): self
    {
        $this->instance->setEndDate($value);
        return $this;
    }

    /**
     * Sets device group field.
     */
    public function deviceGroup(?string $value): self
    {
        $this->instance->setDeviceGroup($value);
        return $this;
    }

    /**
     * Unsets device group field.
     */
    public function unsetDeviceGroup(): self
    {
        $this->instance->unsetDeviceGroup();
        return $this;
    }

    /**
     * Sets device label field.
     */
    public function deviceLabel(?string $value): self
    {
        $this->instance->setDeviceLabel($value);
        return $this;
    }

    /**
     * Unsets device label field.
     */
    public function unsetDeviceLabel(): self
    {
        $this->instance->unsetDeviceLabel();
        return $this;
    }

    /**
     * Sets data plan field.
     */
    public function dataPlan(?string $value): self
    {
        $this->instance->setDataPlan($value);
        return $this;
    }

    /**
     * Unsets data plan field.
     */
    public function unsetDataPlan(): self
    {
        $this->instance->unsetDataPlan();
        return $this;
    }

    /**
     * Sets no session flag field.
     */
    public function noSessionFlag(?string $value): self
    {
        $this->instance->setNoSessionFlag($value);
        return $this;
    }

    /**
     * Initializes a new aggregate session report request object.
     */
    public function build(): AggregateSessionReportRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
