<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\BilledusageListRequest;
use VerizonLib\Models\BillingCycle;
use VerizonLib\Models\LabelsList;

/**
 * Builder for model BilledusageListRequest
 *
 * @see BilledusageListRequest
 */
class BilledusageListRequestBuilder
{
    /**
     * @var BilledusageListRequest
     */
    private $instance;

    private function __construct(BilledusageListRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new billedusage list request Builder object.
     */
    public static function init(string $accountName): self
    {
        return new self(new BilledusageListRequest($accountName));
    }

    /**
     * Sets labels field.
     */
    public function labels(?LabelsList $value): self
    {
        $this->instance->setLabels($value);
        return $this;
    }

    /**
     * Sets device ids field.
     */
    public function deviceIds(?array $value): self
    {
        $this->instance->setDeviceIds($value);
        return $this;
    }

    /**
     * Sets billing cycle field.
     */
    public function billingCycle(?BillingCycle $value): self
    {
        $this->instance->setBillingCycle($value);
        return $this;
    }

    /**
     * Initializes a new billedusage list request object.
     */
    public function build(): BilledusageListRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
