<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\Boundary;

/**
 * Builder for model Boundary
 *
 * @see Boundary
 */
class BoundaryBuilder
{
    /**
     * @var Boundary
     */
    private $instance;

    private function __construct(Boundary $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new boundary Builder object.
     */
    public static function init(): self
    {
        return new self(new Boundary());
    }

    /**
     * Sets csp field.
     */
    public function csp(?string $value): self
    {
        $this->instance->setCsp($value);
        return $this;
    }

    /**
     * Sets region field.
     */
    public function region(?string $value): self
    {
        $this->instance->setRegion($value);
        return $this;
    }

    /**
     * Sets zone id field.
     */
    public function zoneId(?array $value): self
    {
        $this->instance->setZoneId($value);
        return $this;
    }

    /**
     * Initializes a new boundary object.
     */
    public function build(): Boundary
    {
        return CoreHelper::clone($this->instance);
    }
}
