<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\CarrierDeactivateRequest;

/**
 * Builder for model CarrierDeactivateRequest
 *
 * @see CarrierDeactivateRequest
 */
class CarrierDeactivateRequestBuilder
{
    /**
     * @var CarrierDeactivateRequest
     */
    private $instance;

    private function __construct(CarrierDeactivateRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new carrier deactivate request Builder object.
     */
    public static function init(): self
    {
        return new self(new CarrierDeactivateRequest());
    }

    /**
     * Sets account name field.
     */
    public function accountName(?string $value): self
    {
        $this->instance->setAccountName($value);
        return $this;
    }

    /**
     * Sets custom fields field.
     */
    public function customFields(?array $value): self
    {
        $this->instance->setCustomFields($value);
        return $this;
    }

    /**
     * Sets devices field.
     */
    public function devices(?array $value): self
    {
        $this->instance->setDevices($value);
        return $this;
    }

    /**
     * Sets etf waiver field.
     */
    public function etfWaiver(?bool $value): self
    {
        $this->instance->setEtfWaiver($value);
        return $this;
    }

    /**
     * Sets group name field.
     */
    public function groupName(?string $value): self
    {
        $this->instance->setGroupName($value);
        return $this;
    }

    /**
     * Sets reason code field.
     */
    public function reasonCode(?string $value): self
    {
        $this->instance->setReasonCode($value);
        return $this;
    }

    /**
     * Sets service plan field.
     */
    public function servicePlan(?string $value): self
    {
        $this->instance->setServicePlan($value);
        return $this;
    }

    /**
     * Initializes a new carrier deactivate request object.
     */
    public function build(): CarrierDeactivateRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
