<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\Category;

/**
 * Builder for model Category
 *
 * @see Category
 */
class CategoryBuilder
{
    /**
     * @var Category
     */
    private $instance;

    private function __construct(Category $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new category Builder object.
     */
    public static function init(string $categoryName): self
    {
        return new self(new Category($categoryName));
    }

    /**
     * Sets id field.
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets category description field.
     */
    public function categoryDescription(?string $value): self
    {
        $this->instance->setCategoryDescription($value);
        return $this;
    }

    /**
     * Sets is verizon certified field.
     */
    public function isVerizonCertified(?bool $value): self
    {
        $this->instance->setIsVerizonCertified($value);
        return $this;
    }

    /**
     * Sets created date field.
     */
    public function createdDate(?\DateTime $value): self
    {
        $this->instance->setCreatedDate($value);
        return $this;
    }

    /**
     * Sets last modified date field.
     */
    public function lastModifiedDate(?\DateTime $value): self
    {
        $this->instance->setLastModifiedDate($value);
        return $this;
    }

    /**
     * Sets created by field.
     */
    public function createdBy(?string $value): self
    {
        $this->instance->setCreatedBy($value);
        return $this;
    }

    /**
     * Sets updated by field.
     */
    public function updatedBy(?string $value): self
    {
        $this->instance->setUpdatedBy($value);
        return $this;
    }

    /**
     * Initializes a new category object.
     */
    public function build(): Category
    {
        return CoreHelper::clone($this->instance);
    }
}
