<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\ChangePmecDeviceStateDeactivateRequest;

/**
 * Builder for model ChangePmecDeviceStateDeactivateRequest
 *
 * @see ChangePmecDeviceStateDeactivateRequest
 */
class ChangePmecDeviceStateDeactivateRequestBuilder
{
    /**
     * @var ChangePmecDeviceStateDeactivateRequest
     */
    private $instance;

    private function __construct(ChangePmecDeviceStateDeactivateRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new change pmec device state deactivate request Builder object.
     */
    public static function init(string $accountName, array $deviceList): self
    {
        return new self(new ChangePmecDeviceStateDeactivateRequest($accountName, $deviceList));
    }

    /**
     * Initializes a new change pmec device state deactivate request object.
     */
    public function build(): ChangePmecDeviceStateDeactivateRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
