<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\ComputeResourcesType;
use VerizonLib\Models\GPU;

/**
 * Builder for model ComputeResourcesType
 *
 * @see ComputeResourcesType
 */
class ComputeResourcesTypeBuilder
{
    /**
     * @var ComputeResourcesType
     */
    private $instance;

    private function __construct(ComputeResourcesType $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new compute resources type Builder object.
     */
    public static function init(): self
    {
        return new self(new ComputeResourcesType());
    }

    /**
     * Sets gpu field.
     */
    public function gPU(?GPU $value): self
    {
        $this->instance->setGPU($value);
        return $this;
    }

    /**
     * Sets min ramgb field.
     */
    public function minRAMGB(?int $value): self
    {
        $this->instance->setMinRAMGB($value);
        return $this;
    }

    /**
     * Sets min storage gb field.
     */
    public function minStorageGB(?int $value): self
    {
        $this->instance->setMinStorageGB($value);
        return $this;
    }

    /**
     * Initializes a new compute resources type object.
     */
    public function build(): ComputeResourcesType
    {
        return CoreHelper::clone($this->instance);
    }
}
