<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\ConnectionHistoryResult;

/**
 * Builder for model ConnectionHistoryResult
 *
 * @see ConnectionHistoryResult
 */
class ConnectionHistoryResultBuilder
{
    /**
     * @var ConnectionHistoryResult
     */
    private $instance;

    private function __construct(ConnectionHistoryResult $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new connection history result Builder object.
     */
    public static function init(): self
    {
        return new self(new ConnectionHistoryResult());
    }

    /**
     * Sets connection history field.
     */
    public function connectionHistory(?array $value): self
    {
        $this->instance->setConnectionHistory($value);
        return $this;
    }

    /**
     * Sets has more data field.
     */
    public function hasMoreData(?bool $value): self
    {
        $this->instance->setHasMoreData($value);
        return $this;
    }

    /**
     * Initializes a new connection history result object.
     */
    public function build(): ConnectionHistoryResult
    {
        return CoreHelper::clone($this->instance);
    }
}
