<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\ConnectivityManagementSuccessResult;

/**
 * Builder for model ConnectivityManagementSuccessResult
 *
 * @see ConnectivityManagementSuccessResult
 */
class ConnectivityManagementSuccessResultBuilder
{
    /**
     * @var ConnectivityManagementSuccessResult
     */
    private $instance;

    private function __construct(ConnectivityManagementSuccessResult $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new connectivity management success result Builder object.
     */
    public static function init(): self
    {
        return new self(new ConnectivityManagementSuccessResult());
    }

    /**
     * Sets success field.
     */
    public function success(?bool $value): self
    {
        $this->instance->setSuccess($value);
        return $this;
    }

    /**
     * Initializes a new connectivity management success result object.
     */
    public function build(): ConnectivityManagementSuccessResult
    {
        return CoreHelper::clone($this->instance);
    }
}
