<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\ConsentDeleteRequest;

/**
 * Builder for model ConsentDeleteRequest
 *
 * @see ConsentDeleteRequest
 */
class ConsentDeleteRequestBuilder
{
    /**
     * @var ConsentDeleteRequest
     */
    private $instance;

    private function __construct(ConsentDeleteRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new consent delete request Builder object.
     */
    public static function init(): self
    {
        return new self(new ConsentDeleteRequest());
    }

    /**
     * Sets account name field.
     */
    public function accountName(?string $value): self
    {
        $this->instance->setAccountName($value);
        return $this;
    }

    /**
     * Sets device list field.
     */
    public function deviceList(?array $value): self
    {
        $this->instance->setDeviceList($value);
        return $this;
    }

    /**
     * Initializes a new consent delete request object.
     */
    public function build(): ConsentDeleteRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
