<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\CustomWf;
use VerizonLib\Models\Repository;

/**
 * Builder for model CustomWf
 *
 * @see CustomWf
 */
class CustomWfBuilder
{
    /**
     * @var CustomWf
     */
    private $instance;

    private function __construct(CustomWf $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new custom wf Builder object.
     */
    public static function init(): self
    {
        return new self(new CustomWf());
    }

    /**
     * Sets event name field.
     */
    public function eventName(?string $value): self
    {
        $this->instance->setEventName($value);
        return $this;
    }

    /**
     * Sets upload type field.
     */
    public function uploadType(?string $value): self
    {
        $this->instance->setUploadType($value);
        return $this;
    }

    /**
     * Sets repository id field.
     */
    public function repositoryId(?string $value): self
    {
        $this->instance->setRepositoryId($value);
        return $this;
    }

    /**
     * Sets repository field.
     */
    public function repository(?Repository $value): self
    {
        $this->instance->setRepository($value);
        return $this;
    }

    /**
     * Sets source code type field.
     */
    public function sourceCodeType(?string $value): self
    {
        $this->instance->setSourceCodeType($value);
        return $this;
    }

    /**
     * Sets revision type field.
     */
    public function revisionType(?string $value): self
    {
        $this->instance->setRevisionType($value);
        return $this;
    }

    /**
     * Sets name field.
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets path field.
     */
    public function path(?string $value): self
    {
        $this->instance->setPath($value);
        return $this;
    }

    /**
     * Initializes a new custom wf object.
     */
    public function build(): CustomWf
    {
        return CoreHelper::clone($this->instance);
    }
}
