<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\DailyUsageResponse;
use VerizonLib\Models\GIODeviceId;

/**
 * Builder for model DailyUsageResponse
 *
 * @see DailyUsageResponse
 */
class DailyUsageResponseBuilder
{
    /**
     * @var DailyUsageResponse
     */
    private $instance;

    private function __construct(DailyUsageResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new daily usage response Builder object.
     */
    public static function init(): self
    {
        return new self(new DailyUsageResponse());
    }

    /**
     * Sets has more data field.
     */
    public function hasMoreData(?bool $value): self
    {
        $this->instance->setHasMoreData($value);
        return $this;
    }

    /**
     * Sets device id field.
     */
    public function deviceId(?GIODeviceId $value): self
    {
        $this->instance->setDeviceId($value);
        return $this;
    }

    /**
     * Sets usage history field.
     */
    public function usageHistory(?array $value): self
    {
        $this->instance->setUsageHistory($value);
        return $this;
    }

    /**
     * Initializes a new daily usage response object.
     */
    public function build(): DailyUsageResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
