<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\DailyUsageItem;

/**
 * Builder for model DailyUsageItem
 *
 * @see DailyUsageItem
 */
class DailyUsageItemBuilder
{
    /**
     * @var DailyUsageItem
     */
    private $instance;

    private function __construct(DailyUsageItem $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new daily usage item Builder object.
     */
    public static function init(): self
    {
        return new self(new DailyUsageItem());
    }

    /**
     * Sets start time field.
     */
    public function startTime(?string $value): self
    {
        $this->instance->setStartTime($value);
        return $this;
    }

    /**
     * Sets end time field.
     */
    public function endTime(?string $value): self
    {
        $this->instance->setEndTime($value);
        return $this;
    }

    /**
     * Sets num bytes field.
     */
    public function numBytes(?int $value): self
    {
        $this->instance->setNumBytes($value);
        return $this;
    }

    /**
     * Initializes a new daily usage item object.
     */
    public function build(): DailyUsageItem
    {
        return CoreHelper::clone($this->instance);
    }
}
