<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\DailyUsageHistory;

/**
 * Builder for model DailyUsageHistory
 *
 * @see DailyUsageHistory
 */
class DailyUsageHistoryBuilder
{
    /**
     * @var DailyUsageHistory
     */
    private $instance;

    private function __construct(DailyUsageHistory $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new daily usage history Builder object.
     */
    public static function init(): self
    {
        return new self(new DailyUsageHistory());
    }

    /**
     * Sets bytes used field.
     */
    public function bytesUsed(?string $value): self
    {
        $this->instance->setBytesUsed($value);
        return $this;
    }

    /**
     * Sets extended attributes field.
     */
    public function extendedAttributes(?array $value): self
    {
        $this->instance->setExtendedAttributes($value);
        return $this;
    }

    /**
     * Sets service plan field.
     */
    public function servicePlan(?string $value): self
    {
        $this->instance->setServicePlan($value);
        return $this;
    }

    /**
     * Sets sms used field.
     */
    public function smsUsed(?string $value): self
    {
        $this->instance->setSmsUsed($value);
        return $this;
    }

    /**
     * Sets source field.
     */
    public function source(?string $value): self
    {
        $this->instance->setSource($value);
        return $this;
    }

    /**
     * Sets timestamp field.
     */
    public function timestamp(?string $value): self
    {
        $this->instance->setTimestamp($value);
        return $this;
    }

    /**
     * Initializes a new daily usage history object.
     */
    public function build(): DailyUsageHistory
    {
        return CoreHelper::clone($this->instance);
    }
}
