<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\DeactivateDeviceList;

/**
 * Builder for model DeactivateDeviceList
 *
 * @see DeactivateDeviceList
 */
class DeactivateDeviceListBuilder
{
    /**
     * @var DeactivateDeviceList
     */
    private $instance;

    private function __construct(DeactivateDeviceList $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new deactivate device list Builder object.
     */
    public static function init(): self
    {
        return new self(new DeactivateDeviceList());
    }

    /**
     * Sets ids field.
     */
    public function ids(?array $value): self
    {
        $this->instance->setIds($value);
        return $this;
    }

    /**
     * Initializes a new deactivate device list object.
     */
    public function build(): DeactivateDeviceList
    {
        return CoreHelper::clone($this->instance);
    }
}
