<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\DeviceDiagnosticsCallback;

/**
 * Builder for model DeviceDiagnosticsCallback
 *
 * @see DeviceDiagnosticsCallback
 */
class DeviceDiagnosticsCallbackBuilder
{
    /**
     * @var DeviceDiagnosticsCallback
     */
    private $instance;

    private function __construct(DeviceDiagnosticsCallback $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new device diagnostics callback Builder object.
     */
    public static function init(string $accountName, string $serviceName, string $endpoint, \DateTime $createdOn): self
    {
        return new self(new DeviceDiagnosticsCallback($accountName, $serviceName, $endpoint, $createdOn));
    }

    /**
     * Sets http headers field.
     */
    public function httpHeaders(?array $value): self
    {
        $this->instance->setHttpHeaders($value);
        return $this;
    }

    /**
     * Initializes a new device diagnostics callback object.
     */
    public function build(): DeviceDiagnosticsCallback
    {
        return CoreHelper::clone($this->instance);
    }
}
