<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\DeviceAggregateUsageListRequest;

/**
 * Builder for model DeviceAggregateUsageListRequest
 *
 * @see DeviceAggregateUsageListRequest
 */
class DeviceAggregateUsageListRequestBuilder
{
    /**
     * @var DeviceAggregateUsageListRequest
     */
    private $instance;

    private function __construct(DeviceAggregateUsageListRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new device aggregate usage list request Builder object.
     */
    public static function init(string $startTime, string $endTime): self
    {
        return new self(new DeviceAggregateUsageListRequest($startTime, $endTime));
    }

    /**
     * Sets device ids field.
     */
    public function deviceIds(?array $value): self
    {
        $this->instance->setDeviceIds($value);
        return $this;
    }

    /**
     * Sets account name field.
     */
    public function accountName(?string $value): self
    {
        $this->instance->setAccountName($value);
        return $this;
    }

    /**
     * Sets group name field.
     */
    public function groupName(?string $value): self
    {
        $this->instance->setGroupName($value);
        return $this;
    }

    /**
     * Sets label field.
     */
    public function label(?array $value): self
    {
        $this->instance->setLabel($value);
        return $this;
    }

    /**
     * Initializes a new device aggregate usage list request object.
     */
    public function build(): DeviceAggregateUsageListRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
