<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\DevicesConsentResult;

/**
 * Builder for model DevicesConsentResult
 *
 * @see DevicesConsentResult
 */
class DevicesConsentResultBuilder
{
    /**
     * @var DevicesConsentResult
     */
    private $instance;

    private function __construct(DevicesConsentResult $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new devices consent result Builder object.
     */
    public static function init(): self
    {
        return new self(new DevicesConsentResult());
    }

    /**
     * Sets account name field.
     */
    public function accountName(?string $value): self
    {
        $this->instance->setAccountName($value);
        return $this;
    }

    /**
     * Sets all device field.
     */
    public function allDevice(?bool $value): self
    {
        $this->instance->setAllDevice($value);
        return $this;
    }

    /**
     * Sets has more data field.
     */
    public function hasMoreData(?bool $value): self
    {
        $this->instance->setHasMoreData($value);
        return $this;
    }

    /**
     * Sets total count field.
     */
    public function totalCount(?int $value): self
    {
        $this->instance->setTotalCount($value);
        return $this;
    }

    /**
     * Sets update time field.
     */
    public function updateTime(?string $value): self
    {
        $this->instance->setUpdateTime($value);
        return $this;
    }

    /**
     * Sets exclusion field.
     */
    public function exclusion(?array $value): self
    {
        $this->instance->setExclusion($value);
        return $this;
    }

    /**
     * Initializes a new devices consent result object.
     */
    public function build(): DevicesConsentResult
    {
        return CoreHelper::clone($this->instance);
    }
}
