<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\DeviceId;

/**
 * Builder for model DeviceId
 *
 * @see DeviceId
 */
class DeviceIdBuilder
{
    /**
     * @var DeviceId
     */
    private $instance;

    private function __construct(DeviceId $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new device id Builder object.
     */
    public static function init(): self
    {
        return new self(new DeviceId());
    }

    /**
     * Sets id field.
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets kind field.
     */
    public function kind(?string $value): self
    {
        $this->instance->setKind($value);
        return $this;
    }

    /**
     * Initializes a new device id object.
     */
    public function build(): DeviceId
    {
        return CoreHelper::clone($this->instance);
    }
}
