<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\DeviceList1;

/**
 * Builder for model DeviceList1
 *
 * @see DeviceList1
 */
class DeviceList1Builder
{
    /**
     * @var DeviceList1
     */
    private $instance;

    private function __construct(DeviceList1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new device list 1 Builder object.
     */
    public static function init(array $deviceIds, string $ipAddress, string $apn): self
    {
        return new self(new DeviceList1($deviceIds, $ipAddress, $apn));
    }

    /**
     * Initializes a new device list 1 object.
     */
    public function build(): DeviceList1
    {
        return CoreHelper::clone($this->instance);
    }
}
