<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\DeviceConnectionListRequest;
use VerizonLib\Models\DeviceId;

/**
 * Builder for model DeviceConnectionListRequest
 *
 * @see DeviceConnectionListRequest
 */
class DeviceConnectionListRequestBuilder
{
    /**
     * @var DeviceConnectionListRequest
     */
    private $instance;

    private function __construct(DeviceConnectionListRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new device connection list request Builder object.
     */
    public static function init(): self
    {
        return new self(new DeviceConnectionListRequest());
    }

    /**
     * Sets device id field.
     */
    public function deviceId(?DeviceId $value): self
    {
        $this->instance->setDeviceId($value);
        return $this;
    }

    /**
     * Sets earliest field.
     */
    public function earliest(?string $value): self
    {
        $this->instance->setEarliest($value);
        return $this;
    }

    /**
     * Sets latest field.
     */
    public function latest(?string $value): self
    {
        $this->instance->setLatest($value);
        return $this;
    }

    /**
     * Initializes a new device connection list request object.
     */
    public function build(): DeviceConnectionListRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
