<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\DeviceLocationCallback;

/**
 * Builder for model DeviceLocationCallback
 *
 * @see DeviceLocationCallback
 */
class DeviceLocationCallbackBuilder
{
    /**
     * @var DeviceLocationCallback
     */
    private $instance;

    private function __construct(DeviceLocationCallback $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new device location callback Builder object.
     */
    public static function init(string $name, string $url): self
    {
        return new self(new DeviceLocationCallback($name, $url));
    }

    /**
     * Initializes a new device location callback object.
     */
    public function build(): DeviceLocationCallback
    {
        return CoreHelper::clone($this->instance);
    }
}
