<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\DeviceFirmwareUpgrade;

/**
 * Builder for model DeviceFirmwareUpgrade
 *
 * @see DeviceFirmwareUpgrade
 */
class DeviceFirmwareUpgradeBuilder
{
    /**
     * @var DeviceFirmwareUpgrade
     */
    private $instance;

    private function __construct(DeviceFirmwareUpgrade $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new device firmware upgrade Builder object.
     */
    public static function init(
        string $deviceId,
        string $campaignId,
        string $accountName,
        \DateTime $startDate,
        string $status,
        string $reason
    ): self {
        return new self(
            new DeviceFirmwareUpgrade($deviceId, $campaignId, $accountName, $startDate, $status, $reason)
        );
    }

    /**
     * Sets firmware name field.
     */
    public function firmwareName(?string $value): self
    {
        $this->instance->setFirmwareName($value);
        return $this;
    }

    /**
     * Sets firmware from field.
     */
    public function firmwareFrom(?string $value): self
    {
        $this->instance->setFirmwareFrom($value);
        return $this;
    }

    /**
     * Sets firmware to field.
     */
    public function firmwareTo(?string $value): self
    {
        $this->instance->setFirmwareTo($value);
        return $this;
    }

    /**
     * Sets report updated time field.
     */
    public function reportUpdatedTime(?string $value): self
    {
        $this->instance->setReportUpdatedTime($value);
        return $this;
    }

    /**
     * Initializes a new device firmware upgrade object.
     */
    public function build(): DeviceFirmwareUpgrade
    {
        return CoreHelper::clone($this->instance);
    }
}
