<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\DeviceListResult;

/**
 * Builder for model DeviceListResult
 *
 * @see DeviceListResult
 */
class DeviceListResultBuilder
{
    /**
     * @var DeviceListResult
     */
    private $instance;

    private function __construct(DeviceListResult $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new device list result Builder object.
     */
    public static function init(string $accountName, int $deviceCount, array $deviceList): self
    {
        return new self(new DeviceListResult($accountName, $deviceCount, $deviceList));
    }

    /**
     * Initializes a new device list result object.
     */
    public function build(): DeviceListResult
    {
        return CoreHelper::clone($this->instance);
    }
}
