<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\DiagnosticsObservationResult;

/**
 * Builder for model DiagnosticsObservationResult
 *
 * @see DiagnosticsObservationResult
 */
class DiagnosticsObservationResultBuilder
{
    /**
     * @var DiagnosticsObservationResult
     */
    private $instance;

    private function __construct(DiagnosticsObservationResult $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new diagnostics observation result Builder object.
     */
    public static function init(string $transactionID, string $status, \DateTime $createdOn): self
    {
        return new self(new DiagnosticsObservationResult($transactionID, $status, $createdOn));
    }

    /**
     * Initializes a new diagnostics observation result object.
     */
    public function build(): DiagnosticsObservationResult
    {
        return CoreHelper::clone($this->instance);
    }
}
