<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\EdgeServiceOnboardingResult;

/**
 * Builder for model EdgeServiceOnboardingResult
 *
 * @see EdgeServiceOnboardingResult
 */
class EdgeServiceOnboardingResultBuilder
{
    /**
     * @var EdgeServiceOnboardingResult
     */
    private $instance;

    private function __construct(EdgeServiceOnboardingResult $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new edge service onboarding result Builder object.
     */
    public static function init(): self
    {
        return new self(new EdgeServiceOnboardingResult());
    }

    /**
     * Sets code field.
     */
    public function code(?string $value): self
    {
        $this->instance->setCode($value);
        return $this;
    }

    /**
     * Sets message field.
     */
    public function message(?string $value): self
    {
        $this->instance->setMessage($value);
        return $this;
    }

    /**
     * Sets remedy message field.
     */
    public function remedyMessage(?string $value): self
    {
        $this->instance->setRemedyMessage($value);
        return $this;
    }

    /**
     * Initializes a new edge service onboarding result object.
     */
    public function build(): EdgeServiceOnboardingResult
    {
        return CoreHelper::clone($this->instance);
    }
}
