<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\ExtendedAttribute;

/**
 * Builder for model ExtendedAttribute
 *
 * @see ExtendedAttribute
 */
class ExtendedAttributeBuilder
{
    /**
     * @var ExtendedAttribute
     */
    private $instance;

    private function __construct(ExtendedAttribute $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new extended attribute Builder object.
     */
    public static function init(): self
    {
        return new self(new ExtendedAttribute());
    }

    /**
     * Sets key field.
     */
    public function key(?string $value): self
    {
        $this->instance->setKey($value);
        return $this;
    }

    /**
     * Sets value field.
     */
    public function value(?string $value): self
    {
        $this->instance->setValue($value);
        return $this;
    }

    /**
     * Initializes a new extended attribute object.
     */
    public function build(): ExtendedAttribute
    {
        return CoreHelper::clone($this->instance);
    }
}
