<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\FindDeviceByPropertyResponseList;

/**
 * Builder for model FindDeviceByPropertyResponseList
 *
 * @see FindDeviceByPropertyResponseList
 */
class FindDeviceByPropertyResponseListBuilder
{
    /**
     * @var FindDeviceByPropertyResponseList
     */
    private $instance;

    private function __construct(FindDeviceByPropertyResponseList $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new find device by property response list Builder object.
     */
    public static function init(): self
    {
        return new self(new FindDeviceByPropertyResponseList());
    }

    /**
     * Sets device property field.
     */
    public function deviceProperty(?array $value): self
    {
        $this->instance->setDeviceProperty($value);
        return $this;
    }

    /**
     * Initializes a new find device by property response list object.
     */
    public function build(): FindDeviceByPropertyResponseList
    {
        return CoreHelper::clone($this->instance);
    }
}
