<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\FirmwareIMEI;

/**
 * Builder for model FirmwareIMEI
 *
 * @see FirmwareIMEI
 */
class FirmwareIMEIBuilder
{
    /**
     * @var FirmwareIMEI
     */
    private $instance;

    private function __construct(FirmwareIMEI $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new firmware imei Builder object.
     */
    public static function init(array $deviceList): self
    {
        return new self(new FirmwareIMEI($deviceList));
    }

    /**
     * Initializes a new firmware imei object.
     */
    public function build(): FirmwareIMEI
    {
        return CoreHelper::clone($this->instance);
    }
}
