<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\FirmwareUpgradeRequest;

/**
 * Builder for model FirmwareUpgradeRequest
 *
 * @see FirmwareUpgradeRequest
 */
class FirmwareUpgradeRequestBuilder
{
    /**
     * @var FirmwareUpgradeRequest
     */
    private $instance;

    private function __construct(FirmwareUpgradeRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new firmware upgrade request Builder object.
     */
    public static function init(
        string $accountName,
        string $firmwareName,
        string $firmwareTo,
        \DateTime $startDate,
        array $deviceList
    ): self {
        return new self(
            new FirmwareUpgradeRequest($accountName, $firmwareName, $firmwareTo, $startDate, $deviceList)
        );
    }

    /**
     * Initializes a new firmware upgrade request object.
     */
    public function build(): FirmwareUpgradeRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
