<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\FotaV2CallbackRegistrationResult;

/**
 * Builder for model FotaV2CallbackRegistrationResult
 *
 * @see FotaV2CallbackRegistrationResult
 */
class FotaV2CallbackRegistrationResultBuilder
{
    /**
     * @var FotaV2CallbackRegistrationResult
     */
    private $instance;

    private function __construct(FotaV2CallbackRegistrationResult $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new fota v2 callback registration result Builder object.
     */
    public static function init(): self
    {
        return new self(new FotaV2CallbackRegistrationResult());
    }

    /**
     * Sets url field.
     */
    public function url(?string $value): self
    {
        $this->instance->setUrl($value);
        return $this;
    }

    /**
     * Initializes a new fota v2 callback registration result object.
     */
    public function build(): FotaV2CallbackRegistrationResult
    {
        return CoreHelper::clone($this->instance);
    }
}
