<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\FotaV2CallbackRegistrationRequest;

/**
 * Builder for model FotaV2CallbackRegistrationRequest
 *
 * @see FotaV2CallbackRegistrationRequest
 */
class FotaV2CallbackRegistrationRequestBuilder
{
    /**
     * @var FotaV2CallbackRegistrationRequest
     */
    private $instance;

    private function __construct(FotaV2CallbackRegistrationRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new fota v2 callback registration request Builder object.
     */
    public static function init(): self
    {
        return new self(new FotaV2CallbackRegistrationRequest());
    }

    /**
     * Sets url field.
     */
    public function url(?string $value): self
    {
        $this->instance->setUrl($value);
        return $this;
    }

    /**
     * Initializes a new fota v2 callback registration request object.
     */
    public function build(): FotaV2CallbackRegistrationRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
