<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\DeviceIdentifier;
use VerizonLib\Models\GetDeviceExperienceScoreHistoryRequest;

/**
 * Builder for model GetDeviceExperienceScoreHistoryRequest
 *
 * @see GetDeviceExperienceScoreHistoryRequest
 */
class GetDeviceExperienceScoreHistoryRequestBuilder
{
    /**
     * @var GetDeviceExperienceScoreHistoryRequest
     */
    private $instance;

    private function __construct(GetDeviceExperienceScoreHistoryRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new get device experience score history request Builder object.
     */
    public static function init(string $accountName, DeviceIdentifier $deviceId): self
    {
        return new self(new GetDeviceExperienceScoreHistoryRequest($accountName, $deviceId));
    }

    /**
     * Initializes a new get device experience score history request object.
     */
    public function build(): GetDeviceExperienceScoreHistoryRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
