<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\GetPWNPerformanceConsentResponse;

/**
 * Builder for model GetPWNPerformanceConsentResponse
 *
 * @see GetPWNPerformanceConsentResponse
 */
class GetPWNPerformanceConsentResponseBuilder
{
    /**
     * @var GetPWNPerformanceConsentResponse
     */
    private $instance;

    private function __construct(GetPWNPerformanceConsentResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new get pwnperformance consent response Builder object.
     */
    public static function init(): self
    {
        return new self(new GetPWNPerformanceConsentResponse());
    }

    /**
     * Sets consent field.
     */
    public function consent(?string $value): self
    {
        $this->instance->setConsent($value);
        return $this;
    }

    /**
     * Initializes a new get pwnperformance consent response object.
     */
    public function build(): GetPWNPerformanceConsentResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
