<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\GetTriggerResponse;

/**
 * Builder for model GetTriggerResponse
 *
 * @see GetTriggerResponse
 */
class GetTriggerResponseBuilder
{
    /**
     * @var GetTriggerResponse
     */
    private $instance;

    private function __construct(GetTriggerResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new get trigger response Builder object.
     */
    public static function init(): self
    {
        return new self(new GetTriggerResponse());
    }

    /**
     * Sets account name field.
     */
    public function accountName(?string $value): self
    {
        $this->instance->setAccountName($value);
        return $this;
    }

    /**
     * Sets comparator field.
     */
    public function comparator(?string $value): self
    {
        $this->instance->setComparator($value);
        return $this;
    }

    /**
     * Sets created at field.
     */
    public function createdAt(?\DateTime $value): self
    {
        $this->instance->setCreatedAt($value);
        return $this;
    }

    /**
     * Sets group name field.
     */
    public function groupName(?string $value): self
    {
        $this->instance->setGroupName($value);
        return $this;
    }

    /**
     * Sets modified at field.
     */
    public function modifiedAt(?\DateTime $value): self
    {
        $this->instance->setModifiedAt($value);
        return $this;
    }

    /**
     * Sets notification group name field.
     */
    public function notificationGroupName(?string $value): self
    {
        $this->instance->setNotificationGroupName($value);
        return $this;
    }

    /**
     * Sets organization name field.
     */
    public function organizationName(?string $value): self
    {
        $this->instance->setOrganizationName($value);
        return $this;
    }

    /**
     * Sets sms type field.
     */
    public function smsType(?string $value): self
    {
        $this->instance->setSmsType($value);
        return $this;
    }

    /**
     * Sets threshold field.
     */
    public function threshold(?string $value): self
    {
        $this->instance->setThreshold($value);
        return $this;
    }

    /**
     * Sets threshold unit field.
     */
    public function thresholdUnit(?string $value): self
    {
        $this->instance->setThresholdUnit($value);
        return $this;
    }

    /**
     * Sets trigger category field.
     */
    public function triggerCategory(?string $value): self
    {
        $this->instance->setTriggerCategory($value);
        return $this;
    }

    /**
     * Sets trigger cycle field.
     */
    public function triggerCycle(?string $value): self
    {
        $this->instance->setTriggerCycle($value);
        return $this;
    }

    /**
     * Sets trigger id field.
     */
    public function triggerId(?string $value): self
    {
        $this->instance->setTriggerId($value);
        return $this;
    }

    /**
     * Sets trigger name field.
     */
    public function triggerName(?string $value): self
    {
        $this->instance->setTriggerName($value);
        return $this;
    }

    /**
     * Initializes a new get trigger response object.
     */
    public function build(): GetTriggerResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
