<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\GIORequestResponse;

/**
 * Builder for model GIORequestResponse
 *
 * @see GIORequestResponse
 */
class GIORequestResponseBuilder
{
    /**
     * @var GIORequestResponse
     */
    private $instance;

    private function __construct(GIORequestResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new giorequest response Builder object.
     */
    public static function init(): self
    {
        return new self(new GIORequestResponse());
    }

    /**
     * Sets request id field.
     */
    public function requestId(?string $value): self
    {
        $this->instance->setRequestId($value);
        return $this;
    }

    /**
     * Initializes a new giorequest response object.
     */
    public function build(): GIORequestResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
