<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\HyperPreciseLocationFault;

/**
 * Builder for model HyperPreciseLocationFault
 *
 * @see HyperPreciseLocationFault
 */
class HyperPreciseLocationFaultBuilder
{
    /**
     * @var HyperPreciseLocationFault
     */
    private $instance;

    private function __construct(HyperPreciseLocationFault $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new hyper precise location fault Builder object.
     */
    public static function init(): self
    {
        return new self(new HyperPreciseLocationFault());
    }

    /**
     * Sets code field.
     */
    public function code(?string $value): self
    {
        $this->instance->setCode($value);
        return $this;
    }

    /**
     * Sets message field.
     */
    public function message(?string $value): self
    {
        $this->instance->setMessage($value);
        return $this;
    }

    /**
     * Sets description field.
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Initializes a new hyper precise location fault object.
     */
    public function build(): HyperPreciseLocationFault
    {
        return CoreHelper::clone($this->instance);
    }
}
