<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\IntelligenceSuccessResult;

/**
 * Builder for model IntelligenceSuccessResult
 *
 * @see IntelligenceSuccessResult
 */
class IntelligenceSuccessResultBuilder
{
    /**
     * @var IntelligenceSuccessResult
     */
    private $instance;

    private function __construct(IntelligenceSuccessResult $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new intelligence success result Builder object.
     */
    public static function init(): self
    {
        return new self(new IntelligenceSuccessResult());
    }

    /**
     * Sets status field.
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Initializes a new intelligence success result object.
     */
    public function build(): IntelligenceSuccessResult
    {
        return CoreHelper::clone($this->instance);
    }
}
