<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\KeyServicePlan;

/**
 * Builder for model KeyServicePlan
 *
 * @see KeyServicePlan
 */
class KeyServicePlanBuilder
{
    /**
     * @var KeyServicePlan
     */
    private $instance;

    private function __construct(KeyServicePlan $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new key service plan Builder object.
     */
    public static function init(): self
    {
        return new self(new KeyServicePlan());
    }

    /**
     * Sets key field.
     */
    public function key(?string $value): self
    {
        $this->instance->setKey($value);
        return $this;
    }

    /**
     * Initializes a new key service plan object.
     */
    public function build(): KeyServicePlan
    {
        return CoreHelper::clone($this->instance);
    }
}
