<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\ListAllServiceEndpointsResult;

/**
 * Builder for model ListAllServiceEndpointsResult
 *
 * @see ListAllServiceEndpointsResult
 */
class ListAllServiceEndpointsResultBuilder
{
    /**
     * @var ListAllServiceEndpointsResult
     */
    private $instance;

    private function __construct(ListAllServiceEndpointsResult $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new list all service endpoints result Builder object.
     */
    public static function init(): self
    {
        return new self(new ListAllServiceEndpointsResult());
    }

    /**
     * Sets status field.
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Sets data field.
     */
    public function data(?array $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Initializes a new list all service endpoints result object.
     */
    public function build(): ListAllServiceEndpointsResult
    {
        return CoreHelper::clone($this->instance);
    }
}
