<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\M5gBiCustomerName;

/**
 * Builder for model M5gBiCustomerName
 *
 * @see M5gBiCustomerName
 */
class M5gBiCustomerNameBuilder
{
    /**
     * @var M5gBiCustomerName
     */
    private $instance;

    private function __construct(M5gBiCustomerName $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new m5 g bi customer name Builder object.
     */
    public static function init(): self
    {
        return new self(new M5gBiCustomerName());
    }

    /**
     * Sets first name field.
     */
    public function firstName(?string $value): self
    {
        $this->instance->setFirstName($value);
        return $this;
    }

    /**
     * Sets last name field.
     */
    public function lastName(?string $value): self
    {
        $this->instance->setLastName($value);
        return $this;
    }

    /**
     * Sets middle name field.
     */
    public function middleName(?string $value): self
    {
        $this->instance->setMiddleName($value);
        return $this;
    }

    /**
     * Sets title field.
     */
    public function title(?string $value): self
    {
        $this->instance->setTitle($value);
        return $this;
    }

    /**
     * Sets suffex field.
     */
    public function suffex(?string $value): self
    {
        $this->instance->setSuffex($value);
        return $this;
    }

    /**
     * Initializes a new m5 g bi customer name object.
     */
    public function build(): M5gBiCustomerName
    {
        return CoreHelper::clone($this->instance);
    }
}
