<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\M5gBikeyValue1;

/**
 * Builder for model M5gBikeyValue1
 *
 * @see M5gBikeyValue1
 */
class M5gBikeyValue1Builder
{
    /**
     * @var M5gBikeyValue1
     */
    private $instance;

    private function __construct(M5gBikeyValue1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new m5 g bikey value 1 Builder object.
     */
    public static function init(): self
    {
        return new self(new M5gBikeyValue1());
    }

    /**
     * Sets key field.
     */
    public function key(?string $value): self
    {
        $this->instance->setKey($value);
        return $this;
    }

    /**
     * Sets value field.
     */
    public function value(?string $value): self
    {
        $this->instance->setValue($value);
        return $this;
    }

    /**
     * Initializes a new m5 g bikey value 1 object.
     */
    public function build(): M5gBikeyValue1
    {
        return CoreHelper::clone($this->instance);
    }
}
