<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\M5gBiattribute1;

/**
 * Builder for model M5gBiattribute1
 *
 * @see M5gBiattribute1
 */
class M5gBiattribute1Builder
{
    /**
     * @var M5gBiattribute1
     */
    private $instance;

    private function __construct(M5gBiattribute1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new m5 g biattribute 1 Builder object.
     */
    public static function init(): self
    {
        return new self(new M5gBiattribute1());
    }

    /**
     * Sets key field.
     */
    public function key(?string $value): self
    {
        $this->instance->setKey($value);
        return $this;
    }

    /**
     * Initializes a new m5 g biattribute 1 object.
     */
    public function build(): M5gBiattribute1
    {
        return CoreHelper::clone($this->instance);
    }
}
