<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\ManagedAccountsAddResponse;

/**
 * Builder for model ManagedAccountsAddResponse
 *
 * @see ManagedAccountsAddResponse
 */
class ManagedAccountsAddResponseBuilder
{
    /**
     * @var ManagedAccountsAddResponse
     */
    private $instance;

    private function __construct(ManagedAccountsAddResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new managed accounts add response Builder object.
     */
    public static function init(): self
    {
        return new self(new ManagedAccountsAddResponse());
    }

    /**
     * Sets tx id field.
     */
    public function txId(?string $value): self
    {
        $this->instance->setTxId($value);
        return $this;
    }

    /**
     * Sets status list field.
     */
    public function statusList(?array $value): self
    {
        $this->instance->setStatusList($value);
        return $this;
    }

    /**
     * Initializes a new managed accounts add response object.
     */
    public function build(): ManagedAccountsAddResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
