<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\MetadataAnnotation;

/**
 * Builder for model MetadataAnnotation
 *
 * @see MetadataAnnotation
 */
class MetadataAnnotationBuilder
{
    /**
     * @var MetadataAnnotation
     */
    private $instance;

    private function __construct(MetadataAnnotation $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new metadata annotation Builder object.
     */
    public static function init(): self
    {
        return new self(new MetadataAnnotation());
    }

    /**
     * Sets node alpha kubernetes io ttl field.
     */
    public function nodeAlphaKubernetesIoTtl(?string $value): self
    {
        $this->instance->setNodeAlphaKubernetesIoTtl($value);
        return $this;
    }

    /**
     * Sets rafay dev object hash field.
     */
    public function rafayDevObjectHash(?string $value): self
    {
        $this->instance->setRafayDevObjectHash($value);
        return $this;
    }

    /**
     * Sets volumes kubernetes io controller managed attach detach field.
     */
    public function volumesKubernetesIoControllerManagedAttachDetach(?string $value): self
    {
        $this->instance->setVolumesKubernetesIoControllerManagedAttachDetach($value);
        return $this;
    }

    /**
     * Initializes a new metadata annotation object.
     */
    public function build(): MetadataAnnotation
    {
        return CoreHelper::clone($this->instance);
    }
}
