<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\DeviceFilter;
use VerizonLib\Models\MoveDeviceRequest;

/**
 * Builder for model MoveDeviceRequest
 *
 * @see MoveDeviceRequest
 */
class MoveDeviceRequestBuilder
{
    /**
     * @var MoveDeviceRequest
     */
    private $instance;

    private function __construct(MoveDeviceRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new move device request Builder object.
     */
    public static function init(string $accountName): self
    {
        return new self(new MoveDeviceRequest($accountName));
    }

    /**
     * Sets filter field.
     */
    public function filter(?DeviceFilter $value): self
    {
        $this->instance->setFilter($value);
        return $this;
    }

    /**
     * Sets custom fields field.
     */
    public function customFields(?array $value): self
    {
        $this->instance->setCustomFields($value);
        return $this;
    }

    /**
     * Sets devices field.
     */
    public function devices(?array $value): self
    {
        $this->instance->setDevices($value);
        return $this;
    }

    /**
     * Sets group name field.
     */
    public function groupName(?string $value): self
    {
        $this->instance->setGroupName($value);
        return $this;
    }

    /**
     * Sets carrier ip pool name field.
     */
    public function carrierIpPoolName(?string $value): self
    {
        $this->instance->setCarrierIpPoolName($value);
        return $this;
    }

    /**
     * Sets service plan field.
     */
    public function servicePlan(?string $value): self
    {
        $this->instance->setServicePlan($value);
        return $this;
    }

    /**
     * Initializes a new move device request object.
     */
    public function build(): MoveDeviceRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
