<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\Metadata;
use VerizonLib\Models\NodeStatus;
use VerizonLib\Models\NodeStatusItem;
use VerizonLib\Models\ServiceLaunchClusterAdditionalParams;

/**
 * Builder for model NodeStatusItem
 *
 * @see NodeStatusItem
 */
class NodeStatusItemBuilder
{
    /**
     * @var NodeStatusItem
     */
    private $instance;

    private function __construct(NodeStatusItem $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new node status item Builder object.
     */
    public static function init(): self
    {
        return new self(new NodeStatusItem());
    }

    /**
     * Sets metadata field.
     */
    public function metadata(?Metadata $value): self
    {
        $this->instance->setMetadata($value);
        return $this;
    }

    /**
     * Sets spec field.
     */
    public function spec(?ServiceLaunchClusterAdditionalParams $value): self
    {
        $this->instance->setSpec($value);
        return $this;
    }

    /**
     * Sets status field.
     */
    public function status(?NodeStatus $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Initializes a new node status item object.
     */
    public function build(): NodeStatusItem
    {
        return CoreHelper::clone($this->instance);
    }
}
