<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\NotificationGroupNameTriggerAttribute;

/**
 * Builder for model NotificationGroupNameTriggerAttribute
 *
 * @see NotificationGroupNameTriggerAttribute
 */
class NotificationGroupNameTriggerAttributeBuilder
{
    /**
     * @var NotificationGroupNameTriggerAttribute
     */
    private $instance;

    private function __construct(NotificationGroupNameTriggerAttribute $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new notification group name trigger attribute Builder object.
     */
    public static function init(): self
    {
        return new self(new NotificationGroupNameTriggerAttribute());
    }

    /**
     * Sets key field.
     */
    public function key(?string $value): self
    {
        $this->instance->setKey($value);
        return $this;
    }

    /**
     * Initializes a new notification group name trigger attribute object.
     */
    public function build(): NotificationGroupNameTriggerAttribute
    {
        return CoreHelper::clone($this->instance);
    }
}
