<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\PWNProfile;

/**
 * Builder for model PWNProfile
 *
 * @see PWNProfile
 */
class PWNProfileBuilder
{
    /**
     * @var PWNProfile
     */
    private $instance;

    private function __construct(PWNProfile $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new pwnprofile Builder object.
     */
    public static function init(): self
    {
        return new self(new PWNProfile());
    }

    /**
     * Sets profile id field.
     */
    public function profileId(?string $value): self
    {
        $this->instance->setProfileId($value);
        return $this;
    }

    /**
     * Sets profile name field.
     */
    public function profileName(?string $value): self
    {
        $this->instance->setProfileName($value);
        return $this;
    }

    /**
     * Initializes a new pwnprofile object.
     */
    public function build(): PWNProfile
    {
        return CoreHelper::clone($this->instance);
    }
}
