<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\QosDeviceId;

/**
 * Builder for model QosDeviceId
 *
 * @see QosDeviceId
 */
class QosDeviceIdBuilder
{
    /**
     * @var QosDeviceId
     */
    private $instance;

    private function __construct(QosDeviceId $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new qos device id Builder object.
     */
    public static function init(): self
    {
        return new self(new QosDeviceId());
    }

    /**
     * Sets id field.
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets kind field.
     */
    public function kind(?string $value): self
    {
        $this->instance->setKind($value);
        return $this;
    }

    /**
     * Initializes a new qos device id object.
     */
    public function build(): QosDeviceId
    {
        return CoreHelper::clone($this->instance);
    }
}
