<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\QueryMECPerformanceMetricsRequest;

/**
 * Builder for model QueryMECPerformanceMetricsRequest
 *
 * @see QueryMECPerformanceMetricsRequest
 */
class QueryMECPerformanceMetricsRequestBuilder
{
    /**
     * @var QueryMECPerformanceMetricsRequest
     */
    private $instance;

    private function __construct(QueryMECPerformanceMetricsRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new query mecperformance metrics request Builder object.
     */
    public static function init(string $iMEI, string $mSISDN): self
    {
        return new self(new QueryMECPerformanceMetricsRequest($iMEI, $mSISDN));
    }

    /**
     * Initializes a new query mecperformance metrics request object.
     */
    public function build(): QueryMECPerformanceMetricsRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
