<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\ReadySimServicePlan;

/**
 * Builder for model ReadySimServicePlan
 *
 * @see ReadySimServicePlan
 */
class ReadySimServicePlanBuilder
{
    /**
     * @var ReadySimServicePlan
     */
    private $instance;

    private function __construct(ReadySimServicePlan $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new ready sim service plan Builder object.
     */
    public static function init(): self
    {
        return new self(new ReadySimServicePlan());
    }

    /**
     * Sets service plan field.
     */
    public function servicePlan(?string $value): self
    {
        $this->instance->setServicePlan($value);
        return $this;
    }

    /**
     * Initializes a new ready sim service plan object.
     */
    public function build(): ReadySimServicePlan
    {
        return CoreHelper::clone($this->instance);
    }
}
