<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\RetrieveMonitorsRequest;

/**
 * Builder for model RetrieveMonitorsRequest
 *
 * @see RetrieveMonitorsRequest
 */
class RetrieveMonitorsRequestBuilder
{
    /**
     * @var RetrieveMonitorsRequest
     */
    private $instance;

    private function __construct(RetrieveMonitorsRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new retrieve monitors request Builder object.
     */
    public static function init(string $accountName, array $devices): self
    {
        return new self(new RetrieveMonitorsRequest($accountName, $devices));
    }

    /**
     * Sets monitor type field.
     */
    public function monitorType(?string $value): self
    {
        $this->instance->setMonitorType($value);
        return $this;
    }

    /**
     * Initializes a new retrieve monitors request object.
     */
    public function build(): RetrieveMonitorsRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
