<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\SecuritySubscription;

/**
 * Builder for model SecuritySubscription
 *
 * @see SecuritySubscription
 */
class SecuritySubscriptionBuilder
{
    /**
     * @var SecuritySubscription
     */
    private $instance;

    private function __construct(SecuritySubscription $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new security subscription Builder object.
     */
    public static function init(): self
    {
        return new self(new SecuritySubscription());
    }

    /**
     * Sets extended attributes field.
     */
    public function extendedAttributes(?array $value): self
    {
        $this->instance->setExtendedAttributes($value);
        return $this;
    }

    /**
     * Sets license assigned field.
     */
    public function licenseAssigned(?int $value): self
    {
        $this->instance->setLicenseAssigned($value);
        return $this;
    }

    /**
     * Sets license available field.
     */
    public function licenseAvailable(?int $value): self
    {
        $this->instance->setLicenseAvailable($value);
        return $this;
    }

    /**
     * Sets license purchased field.
     */
    public function licensePurchased(?int $value): self
    {
        $this->instance->setLicensePurchased($value);
        return $this;
    }

    /**
     * Sets license type field.
     */
    public function licenseType(?string $value): self
    {
        $this->instance->setLicenseType($value);
        return $this;
    }

    /**
     * Sets sku number field.
     */
    public function skuNumber(?string $value): self
    {
        $this->instance->setSkuNumber($value);
        return $this;
    }

    /**
     * Initializes a new security subscription object.
     */
    public function build(): SecuritySubscription
    {
        return CoreHelper::clone($this->instance);
    }
}
