<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\ServiceUsage;

/**
 * Builder for model ServiceUsage
 *
 * @see ServiceUsage
 */
class ServiceUsageBuilder
{
    /**
     * @var ServiceUsage
     */
    private $instance;

    private function __construct(ServiceUsage $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new service usage Builder object.
     */
    public static function init(): self
    {
        return new self(new ServiceUsage());
    }

    /**
     * Sets account name field.
     */
    public function accountName(?string $value): self
    {
        $this->instance->setAccountName($value);
        return $this;
    }

    /**
     * Sets transactions count field.
     */
    public function transactionsCount(?string $value): self
    {
        $this->instance->setTransactionsCount($value);
        return $this;
    }

    /**
     * Initializes a new service usage object.
     */
    public function build(): ServiceUsage
    {
        return CoreHelper::clone($this->instance);
    }
}
