<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\ServiceLaunchClusterAdditionalParams;

/**
 * Builder for model ServiceLaunchClusterAdditionalParams
 *
 * @see ServiceLaunchClusterAdditionalParams
 */
class ServiceLaunchClusterAdditionalParamsBuilder
{
    /**
     * @var ServiceLaunchClusterAdditionalParams
     */
    private $instance;

    private function __construct(ServiceLaunchClusterAdditionalParams $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new service launch cluster additional params Builder object.
     */
    public static function init(): self
    {
        return new self(new ServiceLaunchClusterAdditionalParams());
    }

    /**
     * Sets additional properties field.
     */
    public function additionalProperties(?array $value): self
    {
        $this->instance->setAdditionalProperties($value);
        return $this;
    }

    /**
     * Initializes a new service launch cluster additional params object.
     */
    public function build(): ServiceLaunchClusterAdditionalParams
    {
        return CoreHelper::clone($this->instance);
    }
}
