<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\SMSMessagesQueryResult;

/**
 * Builder for model SMSMessagesQueryResult
 *
 * @see SMSMessagesQueryResult
 */
class SMSMessagesQueryResultBuilder
{
    /**
     * @var SMSMessagesQueryResult
     */
    private $instance;

    private function __construct(SMSMessagesQueryResult $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new smsmessages query result Builder object.
     */
    public static function init(): self
    {
        return new self(new SMSMessagesQueryResult());
    }

    /**
     * Sets has more data field.
     */
    public function hasMoreData(?bool $value): self
    {
        $this->instance->setHasMoreData($value);
        return $this;
    }

    /**
     * Sets messages field.
     */
    public function messages(?array $value): self
    {
        $this->instance->setMessages($value);
        return $this;
    }

    /**
     * Initializes a new smsmessages query result object.
     */
    public function build(): SMSMessagesQueryResult
    {
        return CoreHelper::clone($this->instance);
    }
}
