<?php

declare(strict_types=1);

/*
 * VerizonThingSpaceQualityOfServiceAPIEndpointsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonThingSpaceQualityOfServiceAPIEndpointsLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonThingSpaceQualityOfServiceAPIEndpointsLib\Models\SubscribeRequest;

/**
 * Builder for model SubscribeRequest
 *
 * @see SubscribeRequest
 */
class SubscribeRequestBuilder
{
    /**
     * @var SubscribeRequest
     */
    private $instance;

    private function __construct(SubscribeRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new subscribe request Builder object.
     */
    public static function init(): self
    {
        return new self(new SubscribeRequest());
    }

    /**
     * Sets account name field.
     */
    public function accountName(?string $value): self
    {
        $this->instance->setAccountName($value);
        return $this;
    }

    /**
     * Sets device info field.
     */
    public function deviceInfo(?array $value): self
    {
        $this->instance->setDeviceInfo($value);
        return $this;
    }

    /**
     * Initializes a new subscribe request object.
     */
    public function build(): SubscribeRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
