<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\TargetAuthenticationBodyHeaders;

/**
 * Builder for model TargetAuthenticationBodyHeaders
 *
 * @see TargetAuthenticationBodyHeaders
 */
class TargetAuthenticationBodyHeadersBuilder
{
    /**
     * @var TargetAuthenticationBodyHeaders
     */
    private $instance;

    private function __construct(TargetAuthenticationBodyHeaders $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new target authentication body headers Builder object.
     */
    public static function init(): self
    {
        return new self(new TargetAuthenticationBodyHeaders());
    }

    /**
     * Sets authorization field.
     */
    public function authorization(?string $value): self
    {
        $this->instance->setAuthorization($value);
        return $this;
    }

    /**
     * Sets content type field.
     */
    public function contentType(?string $value): self
    {
        $this->instance->setContentType($value);
        return $this;
    }

    /**
     * Initializes a new target authentication body headers object.
     */
    public function build(): TargetAuthenticationBodyHeaders
    {
        return CoreHelper::clone($this->instance);
    }
}
