<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\TransactionID;

/**
 * Builder for model TransactionID
 *
 * @see TransactionID
 */
class TransactionIDBuilder
{
    /**
     * @var TransactionID
     */
    private $instance;

    private function __construct(TransactionID $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new transaction id Builder object.
     */
    public static function init(): self
    {
        return new self(new TransactionID());
    }

    /**
     * Sets txid field.
     */
    public function txid(?string $value): self
    {
        $this->instance->setTxid($value);
        return $this;
    }

    /**
     * Initializes a new transaction id object.
     */
    public function build(): TransactionID
    {
        return CoreHelper::clone($this->instance);
    }
}
