<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\Notification;
use VerizonLib\Models\TriggerType2;
use VerizonLib\Models\UsageAnomalyAttributes;

/**
 * Builder for model TriggerType2
 *
 * @see TriggerType2
 */
class TriggerType2Builder
{
    /**
     * @var TriggerType2
     */
    private $instance;

    private function __construct(TriggerType2 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new trigger type 2 Builder object.
     */
    public static function init(): self
    {
        return new self(new TriggerType2());
    }

    /**
     * Sets anomalyattributes field.
     */
    public function anomalyattributes(?UsageAnomalyAttributes $value): self
    {
        $this->instance->setAnomalyattributes($value);
        return $this;
    }

    /**
     * Sets notification field.
     */
    public function notification(?Notification $value): self
    {
        $this->instance->setNotification($value);
        return $this;
    }

    /**
     * Initializes a new trigger type 2 object.
     */
    public function build(): TriggerType2
    {
        return CoreHelper::clone($this->instance);
    }
}
