<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\UploadConfigurationFilesResponse;

/**
 * Builder for model UploadConfigurationFilesResponse
 *
 * @see UploadConfigurationFilesResponse
 */
class UploadConfigurationFilesResponseBuilder
{
    /**
     * @var UploadConfigurationFilesResponse
     */
    private $instance;

    private function __construct(UploadConfigurationFilesResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new upload configuration files response Builder object.
     */
    public static function init(): self
    {
        return new self(new UploadConfigurationFilesResponse());
    }

    /**
     * Sets file name field.
     */
    public function fileName(?string $value): self
    {
        $this->instance->setFileName($value);
        return $this;
    }

    /**
     * Sets file version field.
     */
    public function fileVersion(?string $value): self
    {
        $this->instance->setFileVersion($value);
        return $this;
    }

    /**
     * Sets launch date field.
     */
    public function launchDate(?\DateTime $value): self
    {
        $this->instance->setLaunchDate($value);
        return $this;
    }

    /**
     * Sets release note field.
     */
    public function releaseNote(?string $value): self
    {
        $this->instance->setReleaseNote($value);
        return $this;
    }

    /**
     * Sets model field.
     */
    public function model(?string $value): self
    {
        $this->instance->setModel($value);
        return $this;
    }

    /**
     * Sets make field.
     */
    public function make(?string $value): self
    {
        $this->instance->setMake($value);
        return $this;
    }

    /**
     * Sets distribution type field.
     */
    public function distributionType(?string $value): self
    {
        $this->instance->setDistributionType($value);
        return $this;
    }

    /**
     * Sets device platform id field.
     */
    public function devicePlatformId(?string $value): self
    {
        $this->instance->setDevicePlatformId($value);
        return $this;
    }

    /**
     * Sets local target path field.
     */
    public function localTargetPath(?string $value): self
    {
        $this->instance->setLocalTargetPath($value);
        return $this;
    }

    /**
     * Initializes a new upload configuration files response object.
     */
    public function build(): UploadConfigurationFilesResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
