<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\V1AccountSubscription;

/**
 * Builder for model V1AccountSubscription
 *
 * @see V1AccountSubscription
 */
class V1AccountSubscriptionBuilder
{
    /**
     * @var V1AccountSubscription
     */
    private $instance;

    private function __construct(V1AccountSubscription $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new v1 account subscription Builder object.
     */
    public static function init(): self
    {
        return new self(new V1AccountSubscription());
    }

    /**
     * Sets account name field.
     */
    public function accountName(?string $value): self
    {
        $this->instance->setAccountName($value);
        return $this;
    }

    /**
     * Sets purchase type field.
     */
    public function purchaseType(?string $value): self
    {
        $this->instance->setPurchaseType($value);
        return $this;
    }

    /**
     * Sets license count field.
     */
    public function licenseCount(?int $value): self
    {
        $this->instance->setLicenseCount($value);
        return $this;
    }

    /**
     * Sets license used count field.
     */
    public function licenseUsedCount(?int $value): self
    {
        $this->instance->setLicenseUsedCount($value);
        return $this;
    }

    /**
     * Sets update time field.
     */
    public function updateTime(?string $value): self
    {
        $this->instance->setUpdateTime($value);
        return $this;
    }

    /**
     * Initializes a new v1 account subscription object.
     */
    public function build(): V1AccountSubscription
    {
        return CoreHelper::clone($this->instance);
    }
}
