<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\V2AccountDeviceList;

/**
 * Builder for model V2AccountDeviceList
 *
 * @see V2AccountDeviceList
 */
class V2AccountDeviceListBuilder
{
    /**
     * @var V2AccountDeviceList
     */
    private $instance;

    private function __construct(V2AccountDeviceList $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new v2 account device list Builder object.
     */
    public static function init(string $accountName, bool $hasMoreData, int $maxPageSize, array $deviceList): self
    {
        return new self(new V2AccountDeviceList($accountName, $hasMoreData, $maxPageSize, $deviceList));
    }

    /**
     * Sets last seen device id field.
     */
    public function lastSeenDeviceId(?string $value): self
    {
        $this->instance->setLastSeenDeviceId($value);
        return $this;
    }

    /**
     * Initializes a new v2 account device list object.
     */
    public function build(): V2AccountDeviceList
    {
        return CoreHelper::clone($this->instance);
    }
}
