<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models;

use stdClass;

/**
 * Filter for a list of devices.
 */
class AccountDeviceListFilter implements \JsonSerializable
{
    /**
     * @var DeviceIdSearch[]
     */
    private $deviceIdentifierFilters;

    /**
     * @param DeviceIdSearch[] $deviceIdentifierFilters
     */
    public function __construct(array $deviceIdentifierFilters)
    {
        $this->deviceIdentifierFilters = $deviceIdentifierFilters;
    }

    /**
     * Returns Device Identifier Filters.
     * Specify the kind of the device identifier, the type of match, and the string that you want to match.
     *
     * @return DeviceIdSearch[]
     */
    public function getDeviceIdentifierFilters(): array
    {
        return $this->deviceIdentifierFilters;
    }

    /**
     * Sets Device Identifier Filters.
     * Specify the kind of the device identifier, the type of match, and the string that you want to match.
     *
     * @required
     * @maps deviceIdentifierFilters
     *
     * @param DeviceIdSearch[] $deviceIdentifierFilters
     */
    public function setDeviceIdentifierFilters(array $deviceIdentifierFilters): void
    {
        $this->deviceIdentifierFilters = $deviceIdentifierFilters;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['deviceIdentifierFilters'] = $this->deviceIdentifierFilters;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
