<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models;

use stdClass;

class AssociateLabelRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $accountName;

    /**
     * @var AccountLabels
     */
    private $labels;

    /**
     * @param string $accountName
     * @param AccountLabels $labels
     */
    public function __construct(string $accountName, AccountLabels $labels)
    {
        $this->accountName = $accountName;
        $this->labels = $labels;
    }

    /**
     * Returns Account Name.
     * The name of a billing account. An account name is usually numeric, and must include any leading
     * zeros.
     */
    public function getAccountName(): string
    {
        return $this->accountName;
    }

    /**
     * Sets Account Name.
     * The name of a billing account. An account name is usually numeric, and must include any leading
     * zeros.
     *
     * @required
     * @maps accountName
     */
    public function setAccountName(string $accountName): void
    {
        $this->accountName = $accountName;
    }

    /**
     * Returns Labels.
     * Maximum of 2,000 objects are allowed in the array.
     */
    public function getLabels(): AccountLabels
    {
        return $this->labels;
    }

    /**
     * Sets Labels.
     * Maximum of 2,000 objects are allowed in the array.
     *
     * @required
     * @maps labels
     */
    public function setLabels(AccountLabels $labels): void
    {
        $this->labels = $labels;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['accountName'] = $this->accountName;
        $json['labels']      = $this->labels;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
