<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models;

use stdClass;

/**
 * Account number and list of devices.
 */
class BullseyeServiceRequest implements \JsonSerializable
{
    /**
     * @var DeviceServiceRequest[]
     */
    private $deviceList;

    /**
     * @var string
     */
    private $accountNumber;

    /**
     * @param DeviceServiceRequest[] $deviceList
     * @param string $accountNumber
     */
    public function __construct(array $deviceList, string $accountNumber)
    {
        $this->deviceList = $deviceList;
        $this->accountNumber = $accountNumber;
    }

    /**
     * Returns Device List.
     * A list of devices.
     *
     * @return DeviceServiceRequest[]
     */
    public function getDeviceList(): array
    {
        return $this->deviceList;
    }

    /**
     * Sets Device List.
     * A list of devices.
     *
     * @required
     * @maps deviceList
     *
     * @param DeviceServiceRequest[] $deviceList
     */
    public function setDeviceList(array $deviceList): void
    {
        $this->deviceList = $deviceList;
    }

    /**
     * Returns Account Number.
     * A unique identifier for an account.
     */
    public function getAccountNumber(): string
    {
        return $this->accountNumber;
    }

    /**
     * Sets Account Number.
     * A unique identifier for an account.
     *
     * @required
     * @maps accountNumber
     */
    public function setAccountNumber(string $accountNumber): void
    {
        $this->accountNumber = $accountNumber;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['deviceList']    = $this->deviceList;
        $json['accountNumber'] = $this->accountNumber;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
