<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models;

use stdClass;

class Carrier implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $carriers;

    /**
     * Returns Carriers.
     * The list of carriers with active or available profiles
     */
    public function getCarriers(): ?string
    {
        return $this->carriers;
    }

    /**
     * Sets Carriers.
     * The list of carriers with active or available profiles
     *
     * @maps carriers
     */
    public function setCarriers(?string $carriers): void
    {
        $this->carriers = $carriers;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->carriers)) {
            $json['carriers'] = $this->carriers;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
