<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models;

use stdClass;

class ChangePlan implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $triggerDate;

    /**
     * @var SharePlan[]|null
     */
    private $sharePlan;

    /**
     * Returns Trigger Date.
     */
    public function getTriggerDate(): ?string
    {
        return $this->triggerDate;
    }

    /**
     * Sets Trigger Date.
     *
     * @maps triggerDate
     */
    public function setTriggerDate(?string $triggerDate): void
    {
        $this->triggerDate = $triggerDate;
    }

    /**
     * Returns Share Plan.
     *
     * @return SharePlan[]|null
     */
    public function getSharePlan(): ?array
    {
        return $this->sharePlan;
    }

    /**
     * Sets Share Plan.
     *
     * @maps sharePlan
     *
     * @param SharePlan[]|null $sharePlan
     */
    public function setSharePlan(?array $sharePlan): void
    {
        $this->sharePlan = $sharePlan;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->triggerDate)) {
            $json['triggerDate'] = $this->triggerDate;
        }
        if (isset($this->sharePlan)) {
            $json['sharePlan']   = $this->sharePlan;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
