<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models;

use stdClass;

class ESIMGlobalDeviceList implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $accountName;

    /**
     * @var string|null
     */
    private $provisioningStatusFilter;

    /**
     * @var string|null
     */
    private $profileStatusFilter;

    /**
     * @var string|null
     */
    private $carrierNameFilter;

    /**
     * @var DeviceId2[]|null
     */
    private $deviceFilter;

    /**
     * Returns Account Name.
     * The numeric name of the account.
     */
    public function getAccountName(): ?string
    {
        return $this->accountName;
    }

    /**
     * Sets Account Name.
     * The numeric name of the account.
     *
     * @maps accountName
     */
    public function setAccountName(?string $accountName): void
    {
        $this->accountName = $accountName;
    }

    /**
     * Returns Provisioning Status Filter.
     * The last status of the device as a list filter.
     */
    public function getProvisioningStatusFilter(): ?string
    {
        return $this->provisioningStatusFilter;
    }

    /**
     * Sets Provisioning Status Filter.
     * The last status of the device as a list filter.
     *
     * @maps provisioningStatusFilter
     * @factory \VerizonLib\Models\ProvisioningStatusFilterEnum::checkValue
     */
    public function setProvisioningStatusFilter(?string $provisioningStatusFilter): void
    {
        $this->provisioningStatusFilter = $provisioningStatusFilter;
    }

    /**
     * Returns Profile Status Filter.
     * The last status of the device's profile as a filter.
     */
    public function getProfileStatusFilter(): ?string
    {
        return $this->profileStatusFilter;
    }

    /**
     * Sets Profile Status Filter.
     * The last status of the device's profile as a filter.
     *
     * @maps profileStatusFilter
     * @factory \VerizonLib\Models\ProfileStatusFilterEnum::checkValue
     */
    public function setProfileStatusFilter(?string $profileStatusFilter): void
    {
        $this->profileStatusFilter = $profileStatusFilter;
    }

    /**
     * Returns Carrier Name Filter.
     * The cellular service provider.
     */
    public function getCarrierNameFilter(): ?string
    {
        return $this->carrierNameFilter;
    }

    /**
     * Sets Carrier Name Filter.
     * The cellular service provider.
     *
     * @maps carrierNameFilter
     */
    public function setCarrierNameFilter(?string $carrierNameFilter): void
    {
        $this->carrierNameFilter = $carrierNameFilter;
    }

    /**
     * Returns Device Filter.
     * An array of device identifiers to filter the list.
     *
     * @return DeviceId2[]|null
     */
    public function getDeviceFilter(): ?array
    {
        return $this->deviceFilter;
    }

    /**
     * Sets Device Filter.
     * An array of device identifiers to filter the list.
     *
     * @maps deviceFilter
     *
     * @param DeviceId2[]|null $deviceFilter
     */
    public function setDeviceFilter(?array $deviceFilter): void
    {
        $this->deviceFilter = $deviceFilter;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->accountName)) {
            $json['accountName']              = $this->accountName;
        }
        if (isset($this->provisioningStatusFilter)) {
            $json['provisioningStatusFilter'] =
                ProvisioningStatusFilterEnum::checkValue(
                    $this->provisioningStatusFilter
                );
        }
        if (isset($this->profileStatusFilter)) {
            $json['profileStatusFilter']      = ProfileStatusFilterEnum::checkValue($this->profileStatusFilter);
        }
        if (isset($this->carrierNameFilter)) {
            $json['carrierNameFilter']        = $this->carrierNameFilter;
        }
        if (isset($this->deviceFilter)) {
            $json['deviceFilter']             = $this->deviceFilter;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
