<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models;

use stdClass;

/**
 * List of fields affected by the event.
 */
class Fields2 implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $temperature;

    /**
     * Returns Temperature.
     */
    public function getTemperature(): ?string
    {
        return $this->temperature;
    }

    /**
     * Sets Temperature.
     *
     * @maps temperature
     */
    public function setTemperature(?string $temperature): void
    {
        $this->temperature = $temperature;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->temperature)) {
            $json['temperature'] = $this->temperature;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
