<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models;

use stdClass;

/**
 * MEC Performance Consent Response
 */
class GetMECPerformanceConsentResponse implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $consent;

    /**
     * Returns Consent.
     * MEC Performance Consent Response.
     */
    public function getConsent(): ?string
    {
        return $this->consent;
    }

    /**
     * Sets Consent.
     * MEC Performance Consent Response.
     *
     * @maps consent
     */
    public function setConsent(?string $consent): void
    {
        $this->consent = $consent;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->consent)) {
            $json['consent'] = $this->consent;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
