<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models;

use stdClass;

class GIOProfileRequest implements \JsonSerializable
{
    /**
     * @var GIODeviceList[]
     */
    private $devices;

    /**
     * @var string
     */
    private $accountName;

    /**
     * @var string|null
     */
    private $mdnZipCode;

    /**
     * @var string|null
     */
    private $servicePlan;

    /**
     * @param GIODeviceList[] $devices
     * @param string $accountName
     */
    public function __construct(array $devices, string $accountName)
    {
        $this->devices = $devices;
        $this->accountName = $accountName;
    }

    /**
     * Returns Devices.
     *
     * @return GIODeviceList[]
     */
    public function getDevices(): array
    {
        return $this->devices;
    }

    /**
     * Sets Devices.
     *
     * @required
     * @maps devices
     *
     * @param GIODeviceList[] $devices
     */
    public function setDevices(array $devices): void
    {
        $this->devices = $devices;
    }

    /**
     * Returns Account Name.
     */
    public function getAccountName(): string
    {
        return $this->accountName;
    }

    /**
     * Sets Account Name.
     *
     * @required
     * @maps accountName
     */
    public function setAccountName(string $accountName): void
    {
        $this->accountName = $accountName;
    }

    /**
     * Returns Mdn Zip Code.
     */
    public function getMdnZipCode(): ?string
    {
        return $this->mdnZipCode;
    }

    /**
     * Sets Mdn Zip Code.
     *
     * @maps mdnZipCode
     */
    public function setMdnZipCode(?string $mdnZipCode): void
    {
        $this->mdnZipCode = $mdnZipCode;
    }

    /**
     * Returns Service Plan.
     */
    public function getServicePlan(): ?string
    {
        return $this->servicePlan;
    }

    /**
     * Sets Service Plan.
     *
     * @maps servicePlan
     */
    public function setServicePlan(?string $servicePlan): void
    {
        $this->servicePlan = $servicePlan;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['devices']         = $this->devices;
        $json['accountName']     = $this->accountName;
        if (isset($this->mdnZipCode)) {
            $json['mdnZipCode']  = $this->mdnZipCode;
        }
        if (isset($this->servicePlan)) {
            $json['servicePlan'] = $this->servicePlan;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
