<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models;

use stdClass;

/**
 * Response to return an array of all regions in the Verizon 5G Edge service. You can use the region
 * IDs from the response to find optimal Edge platforms or service endpoints.
 */
class ListRegionsResult implements \JsonSerializable
{
    /**
     * @var Region[]|null
     */
    private $regions;

    /**
     * Returns Regions.
     * An array of all regions in the Verizon 5G Edge service.
     *
     * @return Region[]|null
     */
    public function getRegions(): ?array
    {
        return $this->regions;
    }

    /**
     * Sets Regions.
     * An array of all regions in the Verizon 5G Edge service.
     *
     * @maps regions
     *
     * @param Region[]|null $regions
     */
    public function setRegions(?array $regions): void
    {
        $this->regions = $regions;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->regions)) {
            $json['regions'] = $this->regions;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
