<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models;

use stdClass;

class M5gBideviceId implements \JsonSerializable
{
    /**
     * @var M5gBideviceId1|null
     */
    private $deviceId;

    /**
     * Returns Device Id.
     */
    public function getDeviceId(): ?M5gBideviceId1
    {
        return $this->deviceId;
    }

    /**
     * Sets Device Id.
     *
     * @maps deviceId
     */
    public function setDeviceId(?M5gBideviceId1 $deviceId): void
    {
        $this->deviceId = $deviceId;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->deviceId)) {
            $json['deviceId'] = $this->deviceId;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
