<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models;

use stdClass;

/**
 * Position error.
 */
class PositionError implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $time;

    /**
     * @var string|null
     */
    private $utcoffset;

    /**
     * @var string|null
     */
    private $type;

    /**
     * @var string|null
     */
    private $info;

    /**
     * Returns Time.
     * Time location obtained.
     */
    public function getTime(): ?string
    {
        return $this->time;
    }

    /**
     * Sets Time.
     * Time location obtained.
     *
     * @maps time
     */
    public function setTime(?string $time): void
    {
        $this->time = $time;
    }

    /**
     * Returns Utcoffset.
     * UTC offset of time.
     */
    public function getUtcoffset(): ?string
    {
        return $this->utcoffset;
    }

    /**
     * Sets Utcoffset.
     * UTC offset of time.
     *
     * @maps utcoffset
     */
    public function setUtcoffset(?string $utcoffset): void
    {
        $this->utcoffset = $utcoffset;
    }

    /**
     * Returns Type.
     * Error type returned from location server.
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     * Error type returned from location server.
     *
     * @maps type
     */
    public function setType(?string $type): void
    {
        $this->type = $type;
    }

    /**
     * Returns Info.
     * Additional information about the error.
     */
    public function getInfo(): ?string
    {
        return $this->info;
    }

    /**
     * Sets Info.
     * Additional information about the error.
     *
     * @maps info
     */
    public function setInfo(?string $info): void
    {
        $this->info = $info;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->time)) {
            $json['time']      = $this->time;
        }
        if (isset($this->utcoffset)) {
            $json['utcoffset'] = $this->utcoffset;
        }
        if (isset($this->type)) {
            $json['type']      = $this->type;
        }
        if (isset($this->info)) {
            $json['info']      = $this->info;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
