<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models;

use stdClass;

class QosDeviceInfo implements \JsonSerializable
{
    /**
     * @var QosDeviceId
     */
    private $deviceId;

    /**
     * @var string|null
     */
    private $deviceIPv6Addr;

    /**
     * @var FlowInfo[]
     */
    private $flowInfo;

    /**
     * @param QosDeviceId $deviceId
     * @param FlowInfo[] $flowInfo
     */
    public function __construct(QosDeviceId $deviceId, array $flowInfo)
    {
        $this->deviceId = $deviceId;
        $this->flowInfo = $flowInfo;
    }

    /**
     * Returns Device Id.
     */
    public function getDeviceId(): QosDeviceId
    {
        return $this->deviceId;
    }

    /**
     * Sets Device Id.
     *
     * @required
     * @maps deviceId
     */
    public function setDeviceId(QosDeviceId $deviceId): void
    {
        $this->deviceId = $deviceId;
    }

    /**
     * Returns Device I Pv 6 Addr.
     */
    public function getDeviceIPv6Addr(): ?string
    {
        return $this->deviceIPv6Addr;
    }

    /**
     * Sets Device I Pv 6 Addr.
     *
     * @maps deviceIPv6Addr
     */
    public function setDeviceIPv6Addr(?string $deviceIPv6Addr): void
    {
        $this->deviceIPv6Addr = $deviceIPv6Addr;
    }

    /**
     * Returns Flow Info.
     *
     * @return FlowInfo[]
     */
    public function getFlowInfo(): array
    {
        return $this->flowInfo;
    }

    /**
     * Sets Flow Info.
     *
     * @required
     * @maps flowInfo
     *
     * @param FlowInfo[] $flowInfo
     */
    public function setFlowInfo(array $flowInfo): void
    {
        $this->flowInfo = $flowInfo;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['deviceId']           = $this->deviceId;
        if (isset($this->deviceIPv6Addr)) {
            $json['deviceIPv6Addr'] = $this->deviceIPv6Addr;
        }
        $json['flowInfo']           = $this->flowInfo;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
