<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models;

use stdClass;

/**
 * Response to delete a service.
 */
class ServiceDeleteResult implements \JsonSerializable
{
    /**
     * @var SelectedService|null
     */
    private $selectedService;

    /**
     * @var DependentService[]|null
     */
    private $dependentService;

    /**
     * @var RunningInstance[]|null
     */
    private $runningInstances;

    /**
     * @var EdgeServiceOnboardingResult|null
     */
    private $errorDetails;

    /**
     * Returns Selected Service.
     * Service which is selected.
     */
    public function getSelectedService(): ?SelectedService
    {
        return $this->selectedService;
    }

    /**
     * Sets Selected Service.
     * Service which is selected.
     *
     * @maps selectedService
     */
    public function setSelectedService(?SelectedService $selectedService): void
    {
        $this->selectedService = $selectedService;
    }

    /**
     * Returns Dependent Service.
     * List of dependent services.
     *
     * @return DependentService[]|null
     */
    public function getDependentService(): ?array
    {
        return $this->dependentService;
    }

    /**
     * Sets Dependent Service.
     * List of dependent services.
     *
     * @maps dependentService
     *
     * @param DependentService[]|null $dependentService
     */
    public function setDependentService(?array $dependentService): void
    {
        $this->dependentService = $dependentService;
    }

    /**
     * Returns Running Instances.
     * List of running Instance.
     *
     * @return RunningInstance[]|null
     */
    public function getRunningInstances(): ?array
    {
        return $this->runningInstances;
    }

    /**
     * Sets Running Instances.
     * List of running Instance.
     *
     * @maps runningInstances
     *
     * @param RunningInstance[]|null $runningInstances
     */
    public function setRunningInstances(?array $runningInstances): void
    {
        $this->runningInstances = $runningInstances;
    }

    /**
     * Returns Error Details.
     * Error response attribute of a service.
     */
    public function getErrorDetails(): ?EdgeServiceOnboardingResult
    {
        return $this->errorDetails;
    }

    /**
     * Sets Error Details.
     * Error response attribute of a service.
     *
     * @maps errorDetails
     */
    public function setErrorDetails(?EdgeServiceOnboardingResult $errorDetails): void
    {
        $this->errorDetails = $errorDetails;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->selectedService)) {
            $json['selectedService']  = $this->selectedService;
        }
        if (isset($this->dependentService)) {
            $json['dependentService'] = $this->dependentService;
        }
        if (isset($this->runningInstances)) {
            $json['runningInstances'] = $this->runningInstances;
        }
        if (isset($this->errorDetails)) {
            $json['errorDetails']     = $this->errorDetails;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
