<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models;

use stdClass;

class ServiceLaunchTerraformGitTag implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $tagName;

    /**
     * @var string|null
     */
    private $terraformPath;

    /**
     * Returns Tag Name.
     */
    public function getTagName(): ?string
    {
        return $this->tagName;
    }

    /**
     * Sets Tag Name.
     *
     * @maps tagName
     */
    public function setTagName(?string $tagName): void
    {
        $this->tagName = $tagName;
    }

    /**
     * Returns Terraform Path.
     */
    public function getTerraformPath(): ?string
    {
        return $this->terraformPath;
    }

    /**
     * Sets Terraform Path.
     *
     * @maps terraformPath
     */
    public function setTerraformPath(?string $terraformPath): void
    {
        $this->terraformPath = $terraformPath;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->tagName)) {
            $json['tagName']       = $this->tagName;
        }
        if (isset($this->terraformPath)) {
            $json['terraformPath'] = $this->terraformPath;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
