<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models;

use stdClass;

class SessionTriggerRequest implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $comparator;

    /**
     * @var int|null
     */
    private $threshold;

    /**
     * Returns Comparator.
     */
    public function getComparator(): ?string
    {
        return $this->comparator;
    }

    /**
     * Sets Comparator.
     *
     * @maps comparator
     */
    public function setComparator(?string $comparator): void
    {
        $this->comparator = $comparator;
    }

    /**
     * Returns Threshold.
     */
    public function getThreshold(): ?int
    {
        return $this->threshold;
    }

    /**
     * Sets Threshold.
     *
     * @maps threshold
     */
    public function setThreshold(?int $threshold): void
    {
        $this->threshold = $threshold;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->comparator)) {
            $json['comparator'] = $this->comparator;
        }
        if (isset($this->threshold)) {
            $json['threshold']  = $this->threshold;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
