<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models;

use stdClass;
use VerizonLib\Utils\DateTimeHelper;

class StatusConditionItem implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $type;

    /**
     * @var string|null
     */
    private $status;

    /**
     * @var \DateTime|null
     */
    private $lastHeartbeatTime;

    /**
     * @var \DateTime|null
     */
    private $lastTransitionTime;

    /**
     * @var string|null
     */
    private $reason;

    /**
     * @var string|null
     */
    private $message;

    /**
     * Returns Type.
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     *
     * @maps type
     */
    public function setType(?string $type): void
    {
        $this->type = $type;
    }

    /**
     * Returns Status.
     */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     *
     * @maps status
     */
    public function setStatus(?string $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Last Heartbeat Time.
     */
    public function getLastHeartbeatTime(): ?\DateTime
    {
        return $this->lastHeartbeatTime;
    }

    /**
     * Sets Last Heartbeat Time.
     *
     * @maps lastHeartbeatTime
     * @factory \VerizonLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setLastHeartbeatTime(?\DateTime $lastHeartbeatTime): void
    {
        $this->lastHeartbeatTime = $lastHeartbeatTime;
    }

    /**
     * Returns Last Transition Time.
     */
    public function getLastTransitionTime(): ?\DateTime
    {
        return $this->lastTransitionTime;
    }

    /**
     * Sets Last Transition Time.
     *
     * @maps lastTransitionTime
     * @factory \VerizonLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setLastTransitionTime(?\DateTime $lastTransitionTime): void
    {
        $this->lastTransitionTime = $lastTransitionTime;
    }

    /**
     * Returns Reason.
     */
    public function getReason(): ?string
    {
        return $this->reason;
    }

    /**
     * Sets Reason.
     *
     * @maps reason
     */
    public function setReason(?string $reason): void
    {
        $this->reason = $reason;
    }

    /**
     * Returns Message.
     */
    public function getMessage(): ?string
    {
        return $this->message;
    }

    /**
     * Sets Message.
     *
     * @maps message
     */
    public function setMessage(?string $message): void
    {
        $this->message = $message;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->type)) {
            $json['type']               = $this->type;
        }
        if (isset($this->status)) {
            $json['status']             = $this->status;
        }
        if (isset($this->lastHeartbeatTime)) {
            $json['lastHeartbeatTime']  = DateTimeHelper::toRfc3339DateTime($this->lastHeartbeatTime);
        }
        if (isset($this->lastTransitionTime)) {
            $json['lastTransitionTime'] = DateTimeHelper::toRfc3339DateTime($this->lastTransitionTime);
        }
        if (isset($this->reason)) {
            $json['reason']             = $this->reason;
        }
        if (isset($this->message)) {
            $json['message']            = $this->message;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
