<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models;

use stdClass;

class StopMonitorRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $accountName;

    /**
     * @var string[]
     */
    private $monitorIds;

    /**
     * @param string $accountName
     * @param string[] $monitorIds
     */
    public function __construct(string $accountName, array $monitorIds)
    {
        $this->accountName = $accountName;
        $this->monitorIds = $monitorIds;
    }

    /**
     * Returns Account Name.
     */
    public function getAccountName(): string
    {
        return $this->accountName;
    }

    /**
     * Sets Account Name.
     *
     * @required
     * @maps accountName
     */
    public function setAccountName(string $accountName): void
    {
        $this->accountName = $accountName;
    }

    /**
     * Returns Monitor Ids.
     *
     * @return string[]
     */
    public function getMonitorIds(): array
    {
        return $this->monitorIds;
    }

    /**
     * Sets Monitor Ids.
     *
     * @required
     * @maps monitorIds
     *
     * @param string[] $monitorIds
     */
    public function setMonitorIds(array $monitorIds): void
    {
        $this->monitorIds = $monitorIds;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['accountName'] = $this->accountName;
        $json['monitorIds']  = $this->monitorIds;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
