<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models;

use stdClass;

class Subrequest implements \JsonSerializable
{
    /**
     * @var GIODeviceId|null
     */
    private $ids;

    /**
     * @var string|null
     */
    private $status;

    /**
     * Returns Ids.
     */
    public function getIds(): ?GIODeviceId
    {
        return $this->ids;
    }

    /**
     * Sets Ids.
     *
     * @maps ids
     */
    public function setIds(?GIODeviceId $ids): void
    {
        $this->ids = $ids;
    }

    /**
     * Returns Status.
     */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     *
     * @maps status
     */
    public function setStatus(?string $status): void
    {
        $this->status = $status;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->ids)) {
            $json['ids']    = $this->ids;
        }
        if (isset($this->status)) {
            $json['status'] = $this->status;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
