<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models;

use stdClass;

/**
 * List of device information for an account.
 */
class V2AccountDeviceList implements \JsonSerializable
{
    /**
     * @var string
     */
    private $accountName;

    /**
     * @var bool
     */
    private $hasMoreData;

    /**
     * @var string|null
     */
    private $lastSeenDeviceId;

    /**
     * @var int
     */
    private $maxPageSize;

    /**
     * @var V2AccountDevice[]
     */
    private $deviceList;

    /**
     * @param string $accountName
     * @param bool $hasMoreData
     * @param int $maxPageSize
     * @param V2AccountDevice[] $deviceList
     */
    public function __construct(string $accountName, bool $hasMoreData, int $maxPageSize, array $deviceList)
    {
        $this->accountName = $accountName;
        $this->hasMoreData = $hasMoreData;
        $this->maxPageSize = $maxPageSize;
        $this->deviceList = $deviceList;
    }

    /**
     * Returns Account Name.
     * Account name.
     */
    public function getAccountName(): string
    {
        return $this->accountName;
    }

    /**
     * Sets Account Name.
     * Account name.
     *
     * @required
     * @maps accountName
     */
    public function setAccountName(string $accountName): void
    {
        $this->accountName = $accountName;
    }

    /**
     * Returns Has More Data.
     * Has more device flag?
     */
    public function getHasMoreData(): bool
    {
        return $this->hasMoreData;
    }

    /**
     * Sets Has More Data.
     * Has more device flag?
     *
     * @required
     * @maps hasMoreData
     */
    public function setHasMoreData(bool $hasMoreData): void
    {
        $this->hasMoreData = $hasMoreData;
    }

    /**
     * Returns Last Seen Device Id.
     * Last seen device identifier.
     */
    public function getLastSeenDeviceId(): ?string
    {
        return $this->lastSeenDeviceId;
    }

    /**
     * Sets Last Seen Device Id.
     * Last seen device identifier.
     *
     * @maps lastSeenDeviceId
     */
    public function setLastSeenDeviceId(?string $lastSeenDeviceId): void
    {
        $this->lastSeenDeviceId = $lastSeenDeviceId;
    }

    /**
     * Returns Max Page Size.
     * Maximum page size.
     */
    public function getMaxPageSize(): int
    {
        return $this->maxPageSize;
    }

    /**
     * Sets Max Page Size.
     * Maximum page size.
     *
     * @required
     * @maps maxPageSize
     */
    public function setMaxPageSize(int $maxPageSize): void
    {
        $this->maxPageSize = $maxPageSize;
    }

    /**
     * Returns Device List.
     * Account device list.
     *
     * @return V2AccountDevice[]
     */
    public function getDeviceList(): array
    {
        return $this->deviceList;
    }

    /**
     * Sets Device List.
     * Account device list.
     *
     * @required
     * @maps deviceList
     *
     * @param V2AccountDevice[] $deviceList
     */
    public function setDeviceList(array $deviceList): void
    {
        $this->deviceList = $deviceList;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['accountName']          = $this->accountName;
        $json['hasMoreData']          = $this->hasMoreData;
        if (isset($this->lastSeenDeviceId)) {
            $json['lastSeenDeviceId'] = $this->lastSeenDeviceId;
        }
        $json['maxPageSize']          = $this->maxPageSize;
        $json['deviceList']           = $this->deviceList;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
